services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ouou
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Amir-169114
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    restart: unless-stopped
    networks:
      - appnet

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ouou
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Amir-169114
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  postgres-data:

networks:
  appnet: