spring.application.name=spring-boot-web-sample
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/ouou?createDatabaseIfNotExist=true
spring.datasource.username=root
server.port = 8084
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true